import type { InnerStoreOptions } from "./types";
import type MetaStore from "./core";
import { whatsType } from "../utils";
import { _RESY_BRAND_ } from "./static";

// Check whether the store is generated by Resy's createStore
export const storeErrorProcessing = (
  store: unknown,
  fnName: "useStore" | "connectStore" | "useSubscription" | "subscribe" | "useComputed",
) => {
  if (__DEV__ && (!(store as MetaStore<any>)?.[_RESY_BRAND_])) {
    throw new Error(
      `resy's ${fnName}(...): Expected the 'store' argument should be generated by resy's createStore(...). `
      + `Instead received: ${whatsType(store).toLocaleLowerCase()}.`
    );
  }
};

// Error processing of data update parameters type
export const stateErrorProcessing = (params: {
  state: unknown;
  fnName?: "setState" | "syncUpdate" | "createStore" | "useConciseState" | "defineStore";
  options?: InnerStoreOptions;
}) => {
  const { state, fnName, options } = params;
  const stateType = whatsType(state);
  if (__DEV__ && stateType !== "Object") {
    throw new Error(
      `resy's ${fnName ?? options?._callerName_}(...): takes an object of state to update or`
      + " a function which returns an object of state."
      + ` Instead received: ${stateType.toLocaleLowerCase()}`
    );
  }
  if (__DEV__ && (state as MetaStore<any>)?.[_RESY_BRAND_]) {
    console.error(
      "Warning: resy's setState、syncUpdate(...): takes a store of generated by resy's"
      + " createStore that's has no update significance!"
    );
  }
};

// Options configuration type error processing of createStore/defineStore
export const optionsErrorProcessing = (
  options?: InnerStoreOptions,
) => {
  const optionsType = whatsType(options);
  const optsExist = optionsType !== "Undefined";
  const urType = typeof options?.unmountRestore;
  const nsType = typeof options?.namespace;

  if (
    __DEV__ && (
      (
        optsExist && optionsType !== "Object"
      ) || (
        optionsType === "Object" && (
          (urType !== "boolean" && urType !== "undefined")
          || (nsType !== "string" && nsType !== "undefined")
        )
      )
    )
  ) {
    throw new Error(
      "resy's createStore/defineStore(...): Expected the last optional 'options' argument to be a StoreOptions type params."
      + ` Instead received: ${optionsType.toLocaleLowerCase()}.`
    );
  }
};

// Parameter type error processing of subscribe
export const subscribeErrorProcessing = (
  listener: unknown,
  stateKeys?: unknown,
) => {
  const listenerType = whatsType(listener);
  const stateKeysType = whatsType(stateKeys);
  if (__DEV__ && listenerType !== "Function") {
    throw new Error(
      "resy's subscribe(...): Expected the first optional 'listener' argument to be a function. "
      + `Instead received: ${listenerType.toLocaleLowerCase()}.`
    );
  }
  if (__DEV__ && stateKeysType !== "Undefined" && (stateKeysType !== "Array" && stateKeysType !== "Set")) {
    throw new Error(
      "resy's subscribe(...): Expected the last optional 'stateKeys' argument to be a array. "
      + `Instead received: ${stateKeysType.toLocaleLowerCase()}.`
    );
  }
};
