import type { PrimitiveState, ValueOf, AnyFn } from "../types";
import type { StoreMap, Store, SignalMapType } from "./types";
import React, { type ReactNode } from "react";
import { PureComponentWithStore } from "../classConnect";
import { whatsType, hasOwnProperty } from "../utils";

/**
 * @description If `enginStore` is a store generated by a hook,
 * it is necessary to pay attention to the rules of hooks.
 * When the rules for hook usage are not met,
 * strive to ensure the code executes safely and returns a value.
 */
const saveRun = <S extends PrimitiveState>(
  key: keyof S,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
  ...args: unknown[]
) => {
  if (typeof value === "function") {
    try {
      return (value as AnyFn).bind(enginStore, ...args)();
    } catch (e) {
      return (value as AnyFn).bind(store, ...args)();
    }
  }
  try {
    return (enginStore as any)[key];
  } catch (e) {
    return value;
  }
};

const signalCore = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
  ...args: unknown[]
) => {
  /**
   * @description class components require connecting to the store via connectStore before they can update and render.
   * Using class components offers more freedom compared to the restrictions of using hooks within functional components,
   * and it's less prone to errors related to the rules of hooks usage.
   * 🌟 This advantage stems from my initial decision not to give up on class components,
   * but instead to continuously seek ways to break through resy's support for class components,
   * laying the foundation for the free use here. I am moved by my past self.
   */
  const viewerKey = `${key as string}_Viewer`;
  if (!signalMap.has(viewerKey)) {
    signalMap.set(
      viewerKey,
      class Viewer extends PureComponentWithStore<Record<string, unknown>, Partial<S>> {
        store = this.connectStore(store);
        render() {
          if (typeof value === "function") {
            return (value as AnyFn).bind(this.store, ...Object.values(this.props))() as ReactNode;
          }
          return this.store[key] as ReactNode;
        }
      },
    );
  }

  const Viewer = signalMap.get(viewerKey) as any;

  // Mark the current element as being in the process of rendering.
  let markAsRendering = false;

  const signalKey = `${key as string}_Signal`;
  if (!signalMap.has(signalKey)) {
    signalMap.set(
      signalKey,
      new Proxy({
        ...<Viewer {...args} />,
        /**
         * @description By using the built-in `Symbol.toPrimitive` symbol,
         * the JavaScript engine is made to search for and invoke an object's `Symbol.toPrimitive` property (if it exists).
         */
        [Symbol.toPrimitive]() {
          return saveRun(key, store, enginStore, value, ...args);
        },
      } as any, {
        get(target: any, prop: string | symbol, receiver: any): any {
          // The current data element is directly rendered as a ReactNode.
          if (prop === "$$typeof") {
            markAsRendering = true;
          }
          if (markAsRendering) {
            return Reflect.get(target, prop, receiver);
          }
          if (prop === "valueOf") {
            return () => saveRun(key, store, enginStore, value, ...args);
          }
          const fnReturnRes = saveRun(key, store, enginStore, value, ...args);
          // Array type
          if (whatsType(fnReturnRes) === "Array" && hasOwnProperty.call(Array.prototype, prop)) {
            return whatsType(Array.prototype[prop as any]) === "Function"
              /**
               * @description It's possible that during array map operations,
               * it will be rendered as a ReactNode,
               * so here we need to attempt using `enginStore`.
               * The "?." operator to ensure security
               */
              ? (...arrayArgs: unknown[]) => (
                (fnReturnRes as unknown[])[prop as any] as AnyFn)(...arrayArgs
              )
              : (fnReturnRes as unknown[])?.[prop as any];
          }
          // Map type
          if (whatsType(fnReturnRes) === "Map" && hasOwnProperty.call(Map.prototype, prop)) {
            return prop !== "size"
              ? (...mapArgs: unknown[]) => ((fnReturnRes as any)[prop as any] as AnyFn)(...mapArgs)
              : (fnReturnRes as any)?.[prop as any];
          }
          // Set type
          if (whatsType(fnReturnRes) === "Set" && hasOwnProperty.call(Set.prototype, prop)) {
            return prop !== "size"
              ? (...setArgs: unknown[]) => ((fnReturnRes as any)[prop as any] as AnyFn)(...setArgs)
              : (fnReturnRes as any)?.[prop as any];
          }
          if (!markAsRendering && prop !== Symbol.toPrimitive) {
            // The "?." operator is used to guard against the possibility of null or undefined values.
            return (fnReturnRes as any)?.[prop];
          }
          return Reflect.get(target, prop, receiver);
        }
      }),
    );
  }
  return signalMap.get(signalKey);
};

/**
 * @description "signal-like"
 */
export const createSignal = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
) => {
  /**
   * @description By passing arguments as props to AnyFnMemo through args,
   * and then converting them back to args from props inside the component using Object.values(props),
   * the functionality of passing arguments to computed properties is achieved,
   * while also having the effect of memoization optimization within the computed property function.
   */
  // Keep the returned function's reference address unchanged.
  if (!signalMap.has(key)) {
    signalMap.set(
      key,
      typeof value === "function"
        ? (...args: unknown[]) => signalCore(key, signalMap, store, enginStore, value, ...args)
        : signalCore(key, signalMap, store, enginStore, value)
    );
  }

  return signalMap.get(key);
};
