import type { PrimitiveState, ValueOf, AnyFn } from "../types";
import type { Store, SignalMapType, SignalGetter, StoreMap, SignalRefType } from "./types";
import React, { memo, useRef, type ReactNode, type FunctionComponent } from "react";
import { PureComponentWithStore } from "../classConnect";
import { whatsType } from "../utils";
import {
  __DEEP_SPLICE_KEY__, __SIGNAL_SUFFIX_KEY__, __VIEWER_SUFFIX_KEY__, signalSymbolPropsSet,
} from "./static";

const reduceGetValue = <S extends PrimitiveState>(
  key: string,
  engineStore: StoreMap<S> | Store<S>,
  reduceInitialValue: any,
  ...args: unknown[]
) => {
  const keys = (key as string).split(__DEEP_SPLICE_KEY__);
  return keys.reduce((prevValue: any, prop: string) => {
    const nextValue = prevValue?.[prop];
    return typeof nextValue === "function"
      // "this" pointer of the function here should be the property object that the function itself is attached to.
      ? nextValue.bind(prevValue, ...args)()
      : nextValue;
  }, reduceInitialValue ?? engineStore);
};

/**
 * @description If `enginStore` is a store generated by a hook,
 * it is necessary to pay attention to the rules of hooks.
 * When the rules for hook usage are not met,
 * strive to ensure the code executes safely and returns a value.
 */
const saveRun = <S extends PrimitiveState>(
  key: keyof S,
  store: Store<S>,
  engineStore: StoreMap<S> | Store<S>,
  reduceInitialValue: any,
  reduceInitialPathKey?: string,
  ...args: unknown[]
) => {
  try {
    return reduceGetValue((reduceInitialPathKey ?? key) as string, engineStore, reduceInitialValue, ...args);
  } catch (e) {
    return reduceGetValue((reduceInitialPathKey ?? key) as string, store, reduceInitialValue, ...args);
  }
};

/**
 * @description create "signal-like"
 */
export const createSignal = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  engineStore: StoreMap<S>,
  reduceInitialValue: any,
  value?: ValueOf<S>,
  reduceInitialPathKey?: string,
) => {
  /**
   * @description By passing arguments as props to AnyFnMemo through args,
   * and then converting them back to args from props inside the component using Object.values(props),
   * the functionality of passing arguments to computed properties is achieved,
   * while also having the effect of memoization optimization within the computed property function.
   */
  if (!signalMap.has(key)) {
    signalMap.set(
      key,
      typeof value === "function"
        ? (...args: unknown[]) => {
          /**
           * @description By using the `reduceInitialPathKey` to focus on the parent property,
           * it avoids the redundant computation of tracing data from the beginning specifically for functions.
           * Here, in order to proxy the data returned from within the function again,
           * it is inevitable to execute the function once more to acquire the returned data.
           * 🌟 Here, the primary goal is to obtain the return value of the function.
           * Therefore, it is not necessary to provide
           * the actual `engineStore` as the `engineStore` parameter in the `saveRun` function;
           * a regular store will suffice.
           */
          const curValue = saveRun(
            (reduceInitialPathKey ?? key) as string, store, store,
            reduceInitialValue, reduceInitialPathKey, ...args
          );
          // eslint-disable-next-line @typescript-eslint/no-use-before-define
          return signalCore(
            key, signalMap, store, engineStore, curValue,
            curValue, reduceInitialPathKey, ...args
          );
        }
        // eslint-disable-next-line @typescript-eslint/no-use-before-define
        : signalCore(
          key, signalMap, store, engineStore,
          reduceInitialValue, value, reduceInitialPathKey,
        ),
    );
  }

  return signalMap.get(key);
};

const signalCore = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  engineStore: StoreMap<S>,
  reduceInitialValue: any,
  value?: ValueOf<S>,
  ...args: unknown[]
) => {
  /**
   * @description class components require connecting to the store via connectStore before they can update and render.
   * Using class components offers more freedom compared to the restrictions of using hooks within functional components,
   * and it's less prone to errors related to the rules of hooks usage.
   * 🌟 This advantage stems from my initial decision not to give up on class components,
   * but instead to continuously seek ways to break through resy's support for class components,
   * laying the foundation for the free use here. I am moved by my past self.
   */
  const viewerKey = `${key as string}${__VIEWER_SUFFIX_KEY__}`;
  if (!signalMap.has(viewerKey)) {
    signalMap.set(
      viewerKey,
      class Viewer extends PureComponentWithStore<Record<string, unknown>, Partial<S>> {
        store = this.connectStore(store);
        render() {
          /**
           * @description Here, the final rendering needs to trace the data property paths from the beginning.
           * This is necessary firstly for accurate rendering,
           * and secondly because it is essential to trace the usage records of data properties from inside the store.
           * Subsequent updates can then perform the corresponding rendering updates based on the records of data references used.
           */
          return (
            reduceGetValue(
              key as string, this.store,
              undefined, ...Object.values(this.props),
            ) ?? null
          ) as ReactNode;
        }
      },
    );
  }

  const Viewer = signalMap.get(viewerKey) as any;

  // Mark the current element as being in the process of rendering.
  let markAsRendering = false;

  const signalKey = `${key as string}${__SIGNAL_SUFFIX_KEY__}`;
  if (!signalMap.has(signalKey)) {
    signalMap.set(
      signalKey,
      /**
       * @description In fact, you cannot predict the final data presentation outcome,
       * as the data might be of a composite type. Therefore,
       * here you can only initially assume the data is of a primitive type to facilitate direct rendering presentation.
       * Hence, here the React element object <Viewer {...args} /> is proxied by default.
       */
      new Proxy({
        ...<Viewer key={key} {...args} />,
        [Symbol.toPrimitive]() {
          return saveRun(key, store, engineStore, undefined, undefined, ...args);
        },
        valueOf() {
          return saveRun(key, store, engineStore, undefined, undefined, ...args);
        },
        /**
         * @description “Symbol.toStringTag” itself is a string property.
         * Here, it is necessary to use a getter in a meta-programming approach
         * to transform it into an executable string function property,
         * allowing it to execute at runtime to save on execution costs via `saveRun`.
         */
        get [Symbol.toStringTag]() {
          return whatsType(saveRun(key, store, engineStore, undefined, undefined, ...args));
        },
        [Symbol.iterator]() {
          return {
            index: -1,
            next() {
              this.index++;
              if (this.index < (value as any[]).length) {
                return {
                  done: false,
                  value: createSignal(
                    `${key as string}${__DEEP_SPLICE_KEY__}${this.index}`,
                    signalMap, store, engineStore, undefined,
                    (value as any)[this.index], undefined,
                  ),
                };
              }
              return { done: true };
            }
          };
        },
      }, {
        get(target: any, prop: string | symbol, receiver: any): any {
          // The current data element is directly rendered as a ReactNode.
          if (prop === "$$typeof") {
            markAsRendering = true;
          }
          /**
           * @description When the original primitive value or stringTag is needed,
           * it may involve some sort of conversion, comparison, and so on.
           * Therefore, an attempt is made here to link the data state through the engineStore.
           */
          if (markAsRendering || signalSymbolPropsSet.has(prop as symbol)) {
            return Reflect.get(target, prop, receiver);
          }
          const type = whatsType(value);

          const nextValue = (value as any)?.[prop];

          // nextKey is also used to ensure the uniqueness of attribute paths
          const nextKey = `${key as string}${__DEEP_SPLICE_KEY__}${prop as string}`;

          try {
            /**
             * @description The size properties of map and set data types are on their instances,
             * so an error will be reported if they are read directly from prototype.
             * In addition to Set and Map types,
             * there are also some other types of data that may encounter errors when accessing instance properties.
             * Therefore, it is executed safely here using try catch.
             */
            if (typeof (globalThis as any)?.[type]?.prototype?.[prop as any] === "function") {
              /**
               * @description Here, we cannot directly replace `(value as any)?.[prop]` with `nextValue`
               * because `nextValue` itself is obtained directly from the prototype chain as an original method.
               * If it's not on the data instance, and we use the prototype method for calling,
               * it will result in an error.
               */
              return (...args: unknown[]) => (
                (saveRun(
                  key, store, engineStore, undefined,
                  undefined, ...args
                ))?.[prop] as AnyFn
              )?.(...args);
            }
            return createSignal(
              nextKey, signalMap, store, engineStore,
              reduceInitialValue, nextValue, prop as string,
            );
          } catch (e) {
            return createSignal(
              nextKey, signalMap, store, engineStore,
              reduceInitialValue, nextValue, prop as string,
            );
          }
        }
      }),
    );
  }
  return signalMap.get(signalKey);
};

/**
 * @description Create a signal space for the rendering
 * @param sg The `SignalGetter` function internally returns an arbitrary renderable result.
 */
export const signal = <T extends ReactNode>(sg: SignalGetter<T>): T => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const sgRef = useRef<SignalRefType<T>>({ sg });

  sgRef.current.sg = sg;

  if (!sgRef.current.Memo) {
    sgRef.current.Memo = memo(
      (() => sgRef.current.sg()) as FunctionComponent,
      () => true,
    );
  }

  const { Memo } = sgRef.current;
  return <Memo /> as T;
};
