import type { PrimitiveState, ValueOf, AnyFn } from "../types";
import type { StoreMap, Store, SignalMapType } from "./types";
import React, { type ReactNode } from "react";
import { PureComponentWithStore } from "../classConnect";
import { whatsType } from "../utils";
import { __SIGNAL_SUFFIX_KEY__, __VIEWER_SUFFIX_KEY__ } from "./static";

/**
 * @description If `enginStore` is a store generated by a hook,
 * it is necessary to pay attention to the rules of hooks.
 * When the rules for hook usage are not met,
 * strive to ensure the code executes safely and returns a value.
 */
const saveRun = <S extends PrimitiveState>(
  key: keyof S,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
  ...args: unknown[]
) => {
  if (typeof value === "function") {
    try {
      return (value as AnyFn).bind(enginStore, ...args)();
    } catch (e) {
      return (value as AnyFn).bind(store, ...args)();
    }
  }
  try {
    return (enginStore as any)[key];
  } catch (e) {
    return value;
  }
};

const signalFnOrPrimitive = (prototype: any, prop: string | symbol, value: any) => (
  typeof prototype[prop as any] === "function"
    ? (...args: unknown[]) => ((value as any)[prop as any] as AnyFn)(...args)
    : (value as any)?.[prop as any]
);

const switchSignalDataType = (
  target: any,
  prop: string | symbol,
  receiver: any,
  value: any,
  markAsRendering: boolean,
) => {
  switch (whatsType(value)) {
    case "String":
      return signalFnOrPrimitive(String.prototype, prop, value);
    case "Number":
      return signalFnOrPrimitive(Number.prototype, prop, value);
    case "Boolean":
      return signalFnOrPrimitive(Boolean.prototype, prop, value);
    case "Object":
      return signalFnOrPrimitive(Object.prototype, prop, value);
    case "Array":
      return signalFnOrPrimitive(Array.prototype, prop, value);
    case "Set":
      return signalFnOrPrimitive(Set.prototype, prop, value);
    case "Map":
      return signalFnOrPrimitive(Map.prototype, prop, value);
    case "Function":
      return signalFnOrPrimitive(Function.prototype, prop, value);
    case "Date":
      return signalFnOrPrimitive(Date.prototype, prop, value);
    case "Symbol":
      return signalFnOrPrimitive(Symbol.prototype, prop, value);
    case "WeakSet":
      return signalFnOrPrimitive(WeakSet.prototype, prop, value);
    case "WeakMap":
      return signalFnOrPrimitive(WeakMap.prototype, prop, value);
    case "RegExp":
      return signalFnOrPrimitive(RegExp.prototype, prop, value);
    case "WeakRef":
      return signalFnOrPrimitive(WeakRef.prototype, prop, value);
    case "BigInt":
      return signalFnOrPrimitive(BigInt.prototype, prop, value);
    case "Window":
      return signalFnOrPrimitive(Window.prototype, prop, value);
    default:
      if (!markAsRendering) {
        // The "?." operator is used to guard against the possibility of null or undefined values.
        return (value as any)?.[prop];
      }
      return Reflect.get(target, prop, receiver);
  }
};

const signalCore = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
  ...args: unknown[]
) => {
  /**
   * @description class components require connecting to the store via connectStore before they can update and render.
   * Using class components offers more freedom compared to the restrictions of using hooks within functional components,
   * and it's less prone to errors related to the rules of hooks usage.
   * 🌟 This advantage stems from my initial decision not to give up on class components,
   * but instead to continuously seek ways to break through resy's support for class components,
   * laying the foundation for the free use here. I am moved by my past self.
   */
  const viewerKey = `${key as string}${__VIEWER_SUFFIX_KEY__}`;
  if (!signalMap.has(viewerKey)) {
    signalMap.set(
      viewerKey,
      class Viewer extends PureComponentWithStore<Record<string, unknown>, Partial<S>> {
        store = this.connectStore(store);
        render() {
          if (typeof value === "function") {
            return ((value as AnyFn).bind(this.store, ...Object.values(this.props))() ?? null) as ReactNode;
          }
          return (this.store[key] ?? null) as ReactNode;
        }
      },
    );
  }

  const Viewer = signalMap.get(viewerKey) as any;

  // Mark the current element as being in the process of rendering.
  let markAsRendering = false;

  const signalKey = `${key as string}${__SIGNAL_SUFFIX_KEY__}`;
  if (!signalMap.has(signalKey)) {
    signalMap.set(
      signalKey,
      new Proxy(<Viewer {...args} />, {
        get(target: any, prop: string | symbol, receiver: any): any {
          // The current data element is directly rendered as a ReactNode.
          if (prop === "$$typeof") {
            markAsRendering = true;
          }
          if (markAsRendering) {
            return Reflect.get(target, prop, receiver);
          }
          const signalValue = saveRun(key, store, enginStore, value, ...args);
          if (prop === "valueOf" || prop === Symbol.toPrimitive) {
            return () => signalValue;
          }
          if (prop === Symbol.toStringTag) {
            return whatsType(signalValue);
          }
          return switchSignalDataType(target, prop, receiver, signalValue, markAsRendering);
        }
      }),
    );
  }
  return signalMap.get(signalKey);
};

/**
 * @description "signal-like"
 */
export const createSignal = <S extends PrimitiveState>(
  key: keyof S,
  signalMap: SignalMapType<S>,
  store: Store<S>,
  enginStore: StoreMap<S>,
  value?: ValueOf<S>,
) => {
  /**
   * @description By passing arguments as props to AnyFnMemo through args,
   * and then converting them back to args from props inside the component using Object.values(props),
   * the functionality of passing arguments to computed properties is achieved,
   * while also having the effect of memoization optimization within the computed property function.
   */
  // Keep the returned function's reference address unchanged.
  if (!signalMap.has(key)) {
    signalMap.set(
      key,
      typeof value === "function"
        ? (...args: unknown[]) => signalCore(key, signalMap, store, enginStore, value, ...args)
        : signalCore(key, signalMap, store, enginStore, value)
    );
  }

  return signalMap.get(key);
};
