// A special identifier within the store generated by createStore
export const __REGENERATIVE_SYSTEM_KEY__ = Symbol("regenerative_system_key");

// The key of useStore
export const __USE_STORE_KEY__ = Symbol("use_store_key");

// The key of store namespace
export const __STORE_NAMESPACE__ = Symbol("store_namespace");

// prefix for getters or computed
export const __GETTERS_PREFIX__ = "$";
