import type { InnerStoreOptions } from "./types";

// A special identifier within the store generated by createStore
export const __RESY_BRAND__ = Symbol.for("_resy_brand_");

// prefix for computed
export const __COMPUTED_PREFIX__ = "$";

export const DEFAULT_OPTIONS: InnerStoreOptions = {
  unmountRestore: true,
  namespace: undefined,
  immutable: undefined,
  __callerName__: "createStore",
};
