// @ts-ignore
// eslint-disable-next-line import/no-unresolved
import { unstable_batchedUpdates } from "react-platform";
import type { Callback } from "./types";

/** Batch processing safety shim */
export const batchUpdateShimRun = (fn: Callback) => fn();

export const batchUpdate = unstable_batchedUpdates || batchUpdateShimRun;

// A special identifier within the store generated by createStore
export const __REGENERATIVE_SYSTEM_KEY__ = Symbol("regenerativeSystemKey");

const NODE_ENV = process.env.NODE_ENV;

if (!NODE_ENV) console.error("NODE_ENV not set");

export const __DEV__ = NODE_ENV === "development";

// The key is for class component connects to store
export const __CONNECT_SYMBOL_KEY__ = Symbol("connectSymbolKey");

// The key of useStore
export const __USE_STORE_KEY__ = Symbol("useStoreKey");

// The key is for data references of class component
export const __CLASS_STATE_REF_SET_KEY__ = Symbol("classStateRefSetKey");

// The key of the set collection of store used internally by the class component
export const __STORES_KEY__ = Symbol("storesKey");

// The key is for unmountHandle of class component
export const __CLASS_UNMOUNT_HANDLE_KEY__ = Symbol("classUnmountHandleKey");

// The key is for initialFnHandle of class component
export const __CLASS_FN_INITIAL_HANDLE_KEY__ = Symbol("classFnInitialHandleKey");
