import { REGENERATIVE_SYSTEM_KEY } from "./static";
import type { PrimitiveState, MapType, State, CreateStoreOptions } from "./model";

/**
 * map转object
 * @description 解决回调参数如果是map的proxy代理的话无法做扩展运算的问题
 * 使用map的foreach也可以，并且在数据量较大的时候比for of更快，
 * 但是这里一般数据量认为不过过大达到百万级别，且在大数据量的时候并没有拉开足够的差距
 * 所以for of的方式依旧是众多方式中最综合高效的方式
 */
export const mapToObject = <S extends PrimitiveState>(map: MapType<S>): S => {
  const object = {} as S;
  for (const [key, value] of map) {
    object[key] = value;
  }
  return object;
};

/**
 * object转map
 * @description 性能相对较高的浅转换
 */
export const objectToMap = <S extends PrimitiveState>(object: S) => Object.keys(object)
  .reduce((prev, key) => {
    prev.set(key, object[key]);
    return prev;
  }, new Map());

export const hasOwnProperty = Object.prototype.hasOwnProperty;

// store传的不是由resy本身的createStore创建产生的store的错误处理
export const storeErrorHandle = <S extends PrimitiveState>(store: S, funcName: "useStore" | "view") => {
  if (!store[REGENERATIVE_SYSTEM_KEY as keyof S]) {
    throw new Error(
      `The store parameter of ${funcName} is not a store created by resty's createStore!`
    );
  }
};

const toString = Object.prototype.toString;

// 数据更新参数报错处理
export const stateErrorHandle = <S extends PrimitiveState>(
  stateParams: State<S>,
  funcName: "setState" | "syncUpdate" | "createStore",
) => {
  if (toString.call(stateParams) !== "[object Object]") {
    throw new Error(
      `resy's ${funcName}(...): takes an object of state variables to update or`
      + " a function which returns an object of state variables."
    );
  }
  if (
    (stateParams as Partial<S>)?.[REGENERATIVE_SYSTEM_KEY as keyof S]
  ) {
    console.error(
      `resy's ${funcName}(...): takes a store of generated by resy's createStore that's has no update significance!`
    );
  }
};

// createStore的options配置错误处理
export const optionsErrorHandle = (options?: CreateStoreOptions) => {
  if (options && typeof options?.unmountRestore !== "boolean") {
    throw new Error("The parameter item unmountRestore of options needs to be a boolean value.");
  }
};

/**
 * store被设置为某对象的原型的错误处理
 * @description 防止有对象继承了createStore生成的代理对象，
 * 同时initialState属性中又有 "属性描述对象" 的get (getter) 或者set (setter) 存取器 的写法
 * 会导致proxy中的receiver对象指向的this上下文对象变化
 * 使得 get / set 所得到的数据产生非期望的数据值
 * set不会影响数据，因为set之后会从proxy的get走，所以只要控制好get即可保证数据的正确性
 * detail course:
 * 为了杜绝这种复杂的易产生bug的问题，所以直接抛出错误，提醒开发者禁止疑难杂症的代码写法
 * 因为不禁止就要既要解决get又要解决set，两方面综合起来很麻烦，
 * 而且本身这种东西就是容易误导人或者说难以理清的写法，禁止是最好的考量
 */
export const protoPointStoreErrorHandle = (receiver: any, store: any) => {
  if (receiver !== store) {
    console.error(
      "Warning: It is not recommended that store be inherited as a prototype object," +
      " because there is no this pointing to the target object corresponding to the Reflect proxy within store!"
    );
  }
};

/**
 * @description 跟进状态map
 * 相较于直接赋值新值的方式也更快
 */
export const followUpMap = <K, V>(map: Map<K, V>) => {
  const mapTemp: Map<K, V> = new Map();
  map.forEach((value, key) => {
    mapTemp.set(key, value);
  });
  return mapTemp;
};

/**
 * 清空对象
 * @description 在未达到百万级别的数据量的时候该实现方式相对具有较大优势
 * 且在即使接近或者达到甚至超过百万级别的数据量的情况下该方式仍然与其他实现方式相差性能不大
 * 所以下面的实现方式仍然是相对最优解
 */
export const clearObject = <S extends PrimitiveState>(object: S) => {
  for (const key in object) {
    if (hasOwnProperty.call(object, key)) {
      delete object[key];
    }
  }
};
